# Generated by Django 5.1.1 on 2025-04-18 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_workoutlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('cycle_length', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CyclePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='api.cycle')),
            ],
        ),
        migrations.CreateModel(
            name='CycleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cycle_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.cyclephase')),
            ],
        ),
        migrations.CreateModel(
            name='CycleLogSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_log_symptoms', to='api.cyclelog')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_log_symptoms', to='api.symptom')),
            ],
        ),
        migrations.AddField(
            model_name='cyclelog',
            name='symptoms',
            field=models.ManyToManyField(blank=True, related_name='cycle_logs', through='api.CycleLogSymptom', to='api.symptom'),
        ),
    ]
