# Generated by Django 5.1.1 on 2025-04-19 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_symptom_cycle_cyclephase_cyclelog_cyclelogsymptom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='cyclephase',
            name='phase_name',
        ),
        migrations.AddField(
            model_name='cyclephase',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cycle_phases', to='api.phase'),
        ),
    ]
