# Generated by Django 5.1.1 on 2025-04-19 00:25

from django.db import migrations

def populate_phase(apps, schema_editor):
    """
    Populate the Phase model with initial data.
    """
    Phase = apps.get_model('api', 'Phase')
    
    # Create initial phases
    phases = ["Menstrual", "Follicular", "Ovulatory", "Luteal"]
    
    for phase in phases:
        Phase.objects.get_or_create(name=phase)


def remove_phases(apps, schema_editor):
    """
    Remove all entries from the Phase model.
    """
    Phase = apps.get_model('api', 'Phase')
    phases = ["Menstrual", "Follicular", "Ovulatory", "Luteal"]
    Phase.objects.filter(name__in=phases).delete() 


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_phase_remove_cyclephase_phase_name_cyclephase_phase'),
    ]

    operations = [
        migrations.RunPython(populate_phase, remove_phases),
    ]
