# Generated by Django 5.1.1 on 2025-04-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20250419_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='follicular_length',
            field=models.PositiveIntegerField(default=9),
        ),
        migrations.AddField(
            model_name='customuser',
            name='luteal_length',
            field=models.PositiveIntegerField(default=13),
        ),
        migrations.AddField(
            model_name='customuser',
            name='menstrual_length',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ovulation_length',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='cycle_length',
            field=models.PositiveIntegerField(default=28),
        ),
    ]
