# Generated by Django 5.1.1 on 2025-04-27 14:53

from django.db import migrations


def create_initial_data(apps, schema_editor):
    """Create initial data for the ExerciseType and Exercise models."""
    ExerciseType = apps.get_model('api', 'ExerciseType')
    Exercise = apps.get_model('api', 'Exercise')

    # ---- Create Exercise Types ----
    compound, _ = ExerciseType.objects.get_or_create(name='Compound')
    isolation, _ = ExerciseType.objects.get_or_create(name='Isolation')
    light_cardio, _ = ExerciseType.objects.get_or_create(name='Light Cardio')
    heavy_cardio, _ = ExerciseType.objects.get_or_create(name='Heavy Cardio')

    # ---- List of exercises ----
    exercises_to_create = [
        # Lower Body Compound Exercises
        ('Squats', compound),
        ('Barbell Squats', compound),
        ('Sumo Squats', compound),
        ('Hack Squat', compound),
        ('Hack Squat Machine', compound),
        ('Smith Machine Squats', compound),
        ('Goblet Squats', compound),
        ('Back Squats', compound),
        ('Front Squats', compound),
        ('Zercher Squats', compound),
        ('Pistol Squats', compound),
        ('Split Squats', compound),
        ('Box Squats', compound),
        ('Landmine Squats', compound),
        ('Jump Squats', compound),
        ('Bulgarian Split Squats', compound),
        ('Deadlift', compound),
        ('Sumo Deadlift', compound),
        ('Romanian Deadlift (RDL)', compound),
        ('Single-Leg RDL', compound),
        ('B-Stance RDL', compound),
        ('Good Mornings', compound),
        ('Lunges', compound),
        ('Side Lunges', compound),
        ('Curtsy Lunges', compound),
        ('Hip Thrusts', compound),
        ('Step-Ups', compound),
        ('Glute Bridge', compound),
        ('Walking Lunge', compound),
        ('Reverse Lunge', compound),
        ('Lateral Lunge', compound),
        ('Leg Press Machine', compound),
        ('Seated Leg Press Machine', compound),
        ('45-Degree Leg Press Machine', compound),
        ('Vertical Leg Press Machine', compound),
        ('Landmine RDL', compound),
        ('Landmine Lunges', compound),
        
        # Lower Body Isolation Exercises
        ('KAS Glute Bridge', isolation),
        ('Cable Kickbacks', isolation),
        ('Cable Abduction', isolation),
        ('Abduction Machine (Outer Thighs)', isolation),
        ('Adduction Machine (Inner Thighs)', isolation),
        ('Hip Abduction', isolation),
        ('Hip Abduction Machine', isolation),
        ('Glute Kickback Machine', isolation),
        ('Leg Extension Machine', isolation),
        ('Hamstring Curl', isolation),
        ('Seated Hamstring Curl Machine', isolation),
        ('Lying Hamstring Curl Machine', isolation),
        ('Standing Hamstring Curl Machine', isolation),
        ('Calf Raises', isolation),
        ('Calf Raise Machine', isolation),
        ('Donkey Calf Raise', isolation),
        ('Single-Leg Glute Bridge', isolation),
        ('Clamshells', isolation),
        ('45-Degree Back Extension Machine (Glutes)', isolation),
        ('Back Extension Machine (Glutes)', isolation),
        ('Hyperextension Machine (Glutes)', isolation),
        ('Cable Pull-Through', isolation),
        ('Donkey Kicks', isolation),
        ('Cable Donkey Kicks', isolation),

        # Arms Compound Exercises
        ('Close-Grip Bench Press', compound),
        ('Close-Grip Push Ups', compound),
        ('Dips', compound),
        ('Tricep Dips', compound),
        ('Seated Dips', compound),
        ('Tricep Dips Machine', compound),
        ('Overhead Press', compound),
        ('Barbell Overhead Press', compound),
        ('Dumbbell Overhead Press', compound),
        ('Push Press', compound),
        ('Chin-Ups', compound),
        ('Pull-Ups', compound),
        ('Seated Dumbbell Shoulder Press', compound),
        ('Shoulder Press', compound),
        ('Dumbbell Shoulder Press', compound),
        ('Shoulder Press Machine', compound),
        ('Arnold Press', compound),
        ('Z-Press', compound),
        ('Seated Floor Press', compound),
        ('Landmine Press', compound),

        # Arms Isolation Exercises
        ('Bicep Curls', isolation),
        ('Barbell Bicep Curls', isolation),
        ('Dumbbell Bicep Curls', isolation),
        ('Cable Bicep Curls', isolation),
        ('Preacher Curls', isolation),
        ('Hammer Curls', isolation),
        ('African Curls', isolation),
        ('Rope Cable Hammer Curls', isolation),
        ('Incline Dumbbell Curls', isolation),
        ('Spider Curls', isolation),
        ('Wrist Curls', isolation),
        ('Reverse Wrist Curls', isolation),
        ('Forearm Curls', isolation),
        ('Dumbbell Tricep Kickback', isolation),
        ('Cable Tricep Pushdown', isolation),
        ('Overhead Cable Tricep Extension', isolation),
        ('Skull Crushers', isolation),
        ('Lying Tricep Extension', isolation),
        ('Dumbbell Overhead Tricep Extension', isolation),
        ('Machine Tricep Extension', isolation),
        ('Lateral Raise', isolation),
        ('Front Raise', isolation),
        ('Dumbbell Lateral Raise', isolation),
        ('Cable Single-Arm Lateral Raise', isolation),
        ('Cable Crossover Lateral Raise', isolation),
        ('Cable Lateral Raise', isolation),
        ('Rear Delt Fly', isolation),
        ('Face Pulls', isolation),
        ('Cable Face Pulls', isolation),
        ('Cable Delt Flies', isolation),
        ('Upward Rope Pulls', isolation),
        ('Upward Rope Face Pulls', isolation),
        ('Rope Upright Row', isolation),
        ('Dumbbell Upright Row', isolation),
        ('Upright Row', isolation),
        ('Shoulder Shrugs', isolation),
        ('Barbell Shrugs', isolation),
        ('Traps Machine', isolation),

        # Chest Compound Exercises
        ('Bench Press', compound),
        ('Barbell Bench Press', compound),
        ('Smith Machine Bench Press', compound),
        ('Wide-Grip Bench Press', compound),
        ('Incline Bench Press', compound),
        ('Decline Bench Press', compound),
        ('Incline Smith Machine Bench Press', compound),
        ('Dumbbell Bench Press', compound),
        ('Dumbbell Incline Bench Press', compound),
        ('Dumbbell Decline Bench Press', compound),
        ('Chest Press Machine', compound),
        ('Chest Press', compound),
        ('Incline Cable Chest Press', compound),
        ('Incline Chest Press Machine', compound),
        ('Push-Ups', compound),
        ('Weighted Push-Ups', compound),
        ('Machine Chest-Fly', compound),

        # Chest Isolation Exercises
        ('Dumbbell Chest Fly', isolation),
        ('Incline Dumbbell Chest Fly', isolation),
        ('Cable Chest Fly', isolation),
        ('Cable Lying Chest Fly', isolation),
        ('Pec Deck Machine', isolation),
        ('Single-Arm Cable Chest Fly', isolation),
        ('Svend Press', isolation),
        ('Resistance Band Chest Fly', isolation),
        ('Machine Fly', isolation),
        ('Cable Crossover', isolation),
        ('Cable Chest Crossover', isolation),
        ('Reverse Cable Chest Fly', isolation),
        ('Landmine Chest Press', isolation),

        # Back Compound Exercises
        ('Pull-Ups', compound),
        ('Assisted Pull-Up Machine', compound),
        ('Lat Pulldown', compound),
        ('Cable Lat Pulldown', compound),
        ('Lat Pulldown Machine', compound),
        ('Single Arm Lat Pulldown', compound),
        ('Barbell Rows', compound),
        ('Cable Seated Rows', compound),
        ('Cable Rows', compound),
        ('Bent-Over Barbell Rows', compound),
        ('Bent-Over Dumbbell Rows', compound),
        ('T-bar Row', compound),
        ('Seated Cable Row', compound),
        ('Inverted Row', compound),
        ('Single-Arm Dumbbell Row', compound),
        ('One-Arm Dumbbell Row', compound),
        ('Chest-Supported Row', compound),
        ('Chest-Supported Row Machine', compound),
        ('Landmine Rows', compound),
        ('Kettlebell Rows', compound),

        # Back Isolation Exercises
        ('Straight-arm Pulldown', isolation),
        ('Cable Straight Arm Pulldown', isolation),
        ('Single-arm Cable Row', isolation),
        ('Kneeling Single-arm Cable Row', isolation),
        ('Back Extension Machine', isolation),
        ('Hyperextensions', isolation),
        ('Reverse Fly Machine', isolation),
        ('Dumbbell Pullover', isolation),
        ('Reverse Pec Deck', isolation),
        ('Reverse Flys', isolation),

        # Core Compound Exercises
        ('Kettlebell Swings', compound),
        ('Battle Ropes', compound),
        ('Plank', compound),

        # Core Isolation Exercises
        ('Ab-Crunch Machine', isolation),
        ('Ab Machine', isolation),
        ('Crunch Machine', isolation),
        ('Crunches', isolation),
        ('Cable Crunches', isolation),
        ('Roman Chair (Back Extension)', isolation),
        ('Ab Coaster', isolation),
        ('Leg Raise Machine', isolation),
        ('Side Plank', isolation),
        ('Bicycle Crunch', isolation),
        ('Leg Raises', isolation),
        ('Flutter Kicks', isolation),
        ('Mountain Climbers', isolation),
        ('Dead Bug', isolation),
        ('Hollow Hold', isolation),
        ('Russian Twists', isolation),
        ('V-Ups', isolation),
        ('Ab Rollouts', isolation),
        ('Toe Touches', isolation),
        ('Hanging Leg Raises', isolation),

        # Cardio Light
        ('Treadmill Walking', light_cardio),
        ('Slow Stairmaster', light_cardio),
        ('Bicycle Machine', light_cardio),
        ('Cycling', light_cardio),
        ('Swimming', light_cardio),
        ('Yoga', light_cardio),
        ('Pilates', light_cardio),
        ('Elliptical Trainer', light_cardio),

        # Cardio Heavy
        ('Treadmill Running', heavy_cardio),
        ('Running', heavy_cardio),
        ('Sprints (Intervals)', heavy_cardio),
        ('Treadmill Sprints', heavy_cardio),
        ('Rowing (High-Intensity)', heavy_cardio),
        ('Cycling (HIIT or Hill Sprints)', heavy_cardio),
        ('Burpees', heavy_cardio),
        ('Jump Rope', heavy_cardio),
        ('Boxing', heavy_cardio),
        ('Kickboxing', heavy_cardio),
        ('Stairmaster Sprints', heavy_cardio)
    ]

    # ---- Create Exercises ----
    for name, exercise_type in exercises_to_create:
        Exercise.objects.get_or_create(name=name, exercise_type=exercise_type)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customuser_follicular_length_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
